services:
  postgres:
    image: postgres:16-alpine
    container_name: db-design-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: dbdesign
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    network_mode: "host"

volumes:
  postgres_data:
